font:
  normal:
    family: Source Code Pro
    style: Regular
  bold:
    family: Source Code Pro
    style: Bold

  italic:
    family: Source Code Pro
    style: Italic

  bold_italic:
    family: Source Code Pro
    style: Bold Italic

  size: 24

shell:
  program: /usr/local/bin/tmux
  args:
    - new-session
    - -A
    - -s
    - main
key_bindings:
  - { key: F, mods: Alt, chars: "\x1BF" }
  - { key: B, mods: Alt, chars: "\x1BB" }

