#!/bin/bash
rsync -avz ~/.bash_aliases .
rsync -avz  ~/.gitconfig .
rsync -avz ~/.tmux.conf .
rsync -avz --exclude 'elpa' --exclude 'eshell' --exclude 'session*' --exclude 'auto-save-list' --exclude 'bak' --exclude '*~' --exclude '*.elc' --exclude '.helm-backup' --exclude '.#*'  --exclude 'recentf'  --exclude 'ido.last' --exclude 'smex-items' --exclude 'ac-comphist.dat' --exclude 'projectile-bookmarks.eld' ~/.emacs.d/ .emacs.d
